[tool.ruff]
line-length = 120

[tool.pylint.format]
max-line-length = 120

[tool.ruff.lint]
# Enable the isort rules.
select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["asmatch"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
