name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv pip install -e .[dev]
      - name: Run mypy
        run: uv run mypy asmatch
      - name: Run tests
        run: uv run pytest -q
