# .github/workflows/coverage.yml
name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Create virtual environment
      run: uv venv

    - name: Install dependencies
      run: uv pip install -e .[dev]

    - name: Run tests and generate coverage report
      run: |
        uv run pytest --cov=asmatch --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Optional for private repos
        fail_ci_if_error: true
