name: Test Suite

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv pip install -e .[dev]

      - name: Run mypy
        run: uv run mypy asmatch

      - name: Run ruff
        run: uv run ruff check .

      - name: Check formatting with black
        run: uv run black --check .

      - name: Run tests
        run: uv run python -m unittest discover -v

      - name: Run pytest
        run: uv run pytest -v
